services:
  web:
    build: .
    container_name: web
    volumes:
      - .:/web
    ports:
      - '3000:3000'
      - '3035:3035'
    stdin_open: true
    tty: true
    depends_on:
      - db
  db:
    image: postgres
    container_name: db
    volumes:
      - ./docker/volumes/database:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: "db"
      POSTGRES_HOST_AUTH_METHOD: "trust"
  selenium:
    container_name: selenium
    image: seleniarm/standalone-chromium:latest
    volumes:
      - ./tmp/files:/home/seluser/Downloads
    ports:
      - "4444:4444"
      - "7900:7900"
